source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.4'

gem 'bootsnap', require: false
gem 'devise'
gem 'devise_token_auth'
gem 'mysql2', '~> 0.5'
gem 'omniauth'
gem 'puma'
gem 'rack-cors'
gem 'rails'
gem 'rails-i18n'
gem 'rubocop', require: false
gem 'rubocop-rails', require: false
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-rails'
  gem 'pry-nav'
end
